apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.141.0
          imagePullPolicy: IfNotPresent
          args: ["--config=/etc/otel/otel-config.yaml"]
          ports:
            - name: grpc
              containerPort: 4317
            - name: prometheus
              containerPort: 8889
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
              readOnly: true
            - name: logs
              mountPath: /var/log
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 0m
              memory: 0Mi
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector
        - name: logs
          hostPath:
            path: /var/log
