apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4317
      targetPort: grpc
    - name: prometheus
      port: 8889
      targetPort: prometheus
  selector:
    app: otel-collector