{
 "title": "Kubernetes",
 "description": "A dashboard to view pod metrics by namespace and pod names.\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster. It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"[[pod]]\", container=~\"[[container]]\", namespace=~\"[[namespace]]\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]]\", container=~\"[[container]]\", namespace=~\"[[namespace]]\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"[[pod]]\", namespace=~\"[[namespace]]\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{pod=~\"[[pod]]\", namespace=~\"[[namespace]]\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}