apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.8.0
          imagePullPolicy: IfNotPresent
          args:
            - "--storage.tsdb.retention.size=1536MB"
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - mountPath: /prometheus
              name: data
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 0m
              memory: 0Mi
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus