apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: star
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grafana.outi.ir
      secretName: grafana-tls
  rules:
    - host: grafana.outi.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: web
