apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: star
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jaeger.outi.ir
      secretName: jaeger
  rules:
    - host: jaeger.outi.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
